sonar.projectKey=reservas-gimnasio-udem
sonar.projectName=Reservas Gimnasio UDEM
sonar.projectVersion=1.0.0

sonar.sources=backend/api,frontend/src
sonar.tests=tests/backend,tests/frontend

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=\
**/__pycache__/**,\
**/*.pyc,\
frontend/node_modules/**,\
frontend/dist/**,\
frontend/coverage/**,\
tests/**,\
**/migrations/**

sonar.test.inclusions=\
tests/backend/**/*.py,\
tests/frontend/**/*.js

sonar.coverage.exclusions=\
database/**,\
k8s/**,\
argocd/**,\
jenkins/**,\
observability/**,\
**/*.config.js,\
backend/manage.py,\
backend/gym_api/**,\
backend/api/urls.py,\
**/Nousadas.*,\
frontend/src/index.jsx,\
frontend/src/App.jsx,\
frontend/src/components/**,\
frontend/src/services/config.js

sonar.sourceEncoding=UTF-8